sudo: false
language: node_js
node_js:
- node
- '8.9'
notifications:
  email: false
script:
- npm run lint
- npm run build
deploy:
  provider: heroku
  app: sleepy-wave-94267
  api_key:
    secure: e/6OWStafEM2Oh3WsUqJNfyZHEswsA7uP9LuOa0pmWIakGIyvR3onlQ4q3T7kwMxJafd1lUp2vT303EaNGR0Qx0z0kgbKiTqzhJ89eoMQ++lfAAhEAUlEnVQLDcM1GaqKBVql1MlOUBYN3jc/sWUKtc6WzP3h5+BNhXLeRrrQgPOtHLjP9zs8jOyd/FPv1fnfecVNfPLfEFHkkWeMf59iEy+4FWTY9WxSR8ZdpgseTH66lZzEILUsC7pzavoScQq9WB96KMmK1en8OVQW1d6WFjf+9s1T3NvzchQgB9j836/M+qdmbu0yVBbwUtcEyNcXJMcKd1y5Y4trqbYoyY4pjF6p831RYYH8WoEH5aHWQUChdBLJqLjEJVg/Gl8AUxO4f2mBVX42SsfZ1vQPbXfs4jMVRT9TWFF7RJ0VsUAXRLUnW7kxLQk43VdOmk0Vsu2SHIN9sjeJtqn82WZS0Vfyyk37cJ9J2Wy+1ttCmW8SIzyIt1k/Pg6eyU02+xJFzuA4q6Up2FWR4zWp6EFfReeJTXTMeqgUj3fIHMZ1YCrV+YXFWKLHeJL1hluIem3xDuYU7+n+tB47s1cHF/0jUrosbBWXhk1eEtHDpFxhdl9jopFkXxTSPL2e+IR+skGWO0K88ecADUvk/RxCqLyt74Wnu6SQIecxkM0k8xgy1yAFe8=
  skip_cleanup: true
